### PR TITLE
Make releaseLayers iterative rather than recursive, remove useless func

### PR DESCRIPTION
**Pull request by aidanhs**
Best reviewed with a diff tool able to ignore whitespace changes (`meld` is such a tool).

The observation I had was that `releaseLayer` is a wrapper for `releaseLayers`, and is actually the only place `releaseLayers` is called. I therefore decided to merge the two functions into one by making the chain traversal process iterative rather than recursive.

### CODE REVIEW

**Comment by aidanhs** [comment]
screenshot - 201115 - 13 46 03

Screenshot of whitespace-agnostic diff in case it helps.

**Comment by aidanhs** [comment]
Minor tweak after golinting: `depth += 1` -> `depth++`.

**Comment by aaronlehmann** [comment]
LGTM

ping @dmcgowan

**Comment by dmcgowan** [comment]
This change looks good. Can you open up a PR against docker master now that it has been merged. Just ping me and Aaron and we should be able to give a quick review. Thanks!

**Pull request closed without merging**
